Release v1.0-SNAPSHOT-20

diff --git a/repositories/snake-noruntime/snapshot/bin/snake b/repositories/snake-noruntime/snapshot/bin/snake
--- a/repositories/snake-noruntime/snapshot/bin/snake
+++ b/repositories/snake-noruntime/snapshot/bin/snake
@@ -22,7 +22,11 @@ while : ; do
             exit 2
         fi
         if ! find . -type f -exec mv -f \{} ../\{} \; ; then
-            echo "$0: Failed to copy update files." >&2
+            echo "$0: Failed to move update files." >&2
+            exit 2
+        fi
+        if ! find . -type l -exec mv -f \{} ../\{} \; ; then
+            echo "$0: Failed to move link files." >&2
             exit 2
         fi
         cd ..
diff --git a/repositories/snake/snapshot/bin/snake b/repositories/snake/snapshot/bin/snake
--- a/repositories/snake/snapshot/bin/snake
+++ b/repositories/snake/snapshot/bin/snake
@@ -2,7 +2,7 @@
 realpath=$(readlink "$0")
 if [ -z "${realpath}" ] ; then realpath="$0" ; fi
 cd $(dirname ${realpath})/..
-VM_OPTIONS="-p app/bootstrap/modulepath/commons-cli.jar:app/bootstrap/modulepath/commons-io.jar:app/bootstrap/modulepath/commons-lang3.jar:app/bootstrap/modulepath/forker-common.jar:app/bootstrap/modulepath/javafx-base.jar:app/bootstrap/modulepath/FX-BorderlessScene.jar:app/bootstrap/modulepath/javafx-base-linux.jar:app/bootstrap/modulepath/javafx-graphics.jar:app/bootstrap/modulepath/jna-platform.jar:app/bootstrap/modulepath/forker-daemon.jar:app/bootstrap/modulepath/snake-updater.jar:app/bootstrap/modulepath/javafx-graphics-linux.jar:app/bootstrap/modulepath/forker-updater.jar:app/bootstrap/modulepath/jna.jar:app/bootstrap/modulepath/forker-wrapper.jar:app/bootstrap/modulepath/javafx-fxml-linux.jar:app/bootstrap/modulepath/forker-client.jar:app/bootstrap/modulepath/javafx-controls.jar:app/bootstrap/modulepath/javafx-fxml.jar:app/bootstrap/modulepath/forker-wrapped.jar:app/bootstrap/modulepath/javafx-controls-linux.jar  --add-modules java.prefs,java.xml,jdk.unsupported,jdk.crypto.ec,java.instrument,java.management,jdk.attach,jdk.management.agent,jdk.xml.dom,jdk.jsobject,java.net.http,java.desktop,java.scripting,java.management,java.sql -Dforker.remoteManifest=http://www.bithatch.co.uk/repositories/snake/snapshot -Xmx64m"
+VM_OPTIONS="-p app/bootstrap/modulepath/commons-cli.jar:app/bootstrap/modulepath/commons-io.jar:app/bootstrap/modulepath/commons-lang3.jar:app/bootstrap/modulepath/forker-common.jar:app/bootstrap/modulepath/javafx-base.jar:app/bootstrap/modulepath/FX-BorderlessScene.jar:app/bootstrap/modulepath/javafx-base-linux.jar:app/bootstrap/modulepath/javafx-graphics.jar:app/bootstrap/modulepath/jna-platform.jar:app/bootstrap/modulepath/forker-daemon.jar:app/bootstrap/modulepath/snake-updater.jar:app/bootstrap/modulepath/javafx-graphics-linux.jar:app/bootstrap/modulepath/forker-updater.jar:app/bootstrap/modulepath/jna.jar:app/bootstrap/modulepath/forker-wrapper.jar:app/bootstrap/modulepath/javafx-fxml-linux.jar:app/bootstrap/modulepath/forker-client.jar:app/bootstrap/modulepath/javafx-controls.jar:app/bootstrap/modulepath/javafx-fxml.jar:app/bootstrap/modulepath/forker-wrapped.jar:app/bootstrap/modulepath/javafx-controls-linux.jar  --add-modules java.prefs,java.xml,jdk.unsupported,jdk.crypto.ec,jdk.zipfs,java.instrument,java.management,jdk.attach,jdk.management.agent,jdk.xml.dom,jdk.jsobject,java.net.http,java.desktop,java.scripting,java.management,java.sql -Dforker.remoteManifest=http://www.bithatch.co.uk/repositories/snake/snapshot -Xmx64m"
 JAVA_EXE=bin/java
 APP_ARGS="--configuration app.cfg"
 while : ; do
@@ -18,7 +18,11 @@ while : ; do
             exit 2
         fi
         if ! find . -type f -exec mv -f \{} ../\{} \; ; then
-            echo "$0: Failed to copy update files." >&2
+            echo "$0: Failed to move update files." >&2
+            exit 2
+        fi
+        if ! find . -type l -exec mv -f \{} ../\{} \; ; then
+            echo "$0: Failed to move link files." >&2
             exit 2
         fi
         cd ..
